services:
  postgres:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-engine:
    build: ./order-engine
    container_name: order-engine
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass
      INTEGRATIONS_PAYMENT_SERVICE_URL: http://payment-service:8081
      INTEGRATIONS_STOCK_SERVICE_URL: http://stock-service:8082
    depends_on:
      - postgres

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      INTEGRATIONS_ORDER_ENGINE_URL: http://order-engine:8080

  stock-service:
    build: ./stock-service
    container_name: stock-service
    ports:
      - "8082:8082"
    environment:
      INTEGRATIONS_ORDER_ENGINE_URL: http://order-engine:8080

volumes:
  postgres_data:
